from pymongo import MongoClient
from datetime import datetime

# MongoDB connection
client = MongoClient("mongodb://localhost:27017/")
db = client["financial_dashboard"]

# Provided transactions data
transactions = [
    {
        "date": "17-Jan-24",
        "refNo": "Txn001",
        "account": "Dummy-123",
        "instrument": "Adani Green Energy Ltd",
        "product": "Equity",
        "securityCode": "ADANIGREEN",
        "txnType": "Sell",
        "quantity": 5,
        "price": 1576.4,
        "amount": 7882,
        "brokerage": 11.5,
        "tax": 0,
    },
    {
        "date": "18-Jan-24",
        "refNo": "Txn112",
        "account": "Dummy-123",
        "instrument": "Cash",
        "product": "Current account",
        "txnType": "Withdrawal",
        "quantity": None,
        "price": None,
        "amount": 20575,
        "brokerage": 0,
        "tax": 0,
    },
    {
        "date": "17-Feb-24",
        "refNo": "Txn109",
        "account": "Dummy-123",
        "instrument": "Adani Green Energy Ltd",
        "product": "Equity",
        "securityCode": "ADANIGREEN",
        "txnType": "Sell",
        "quantity": 14,
        "price": 1072.07,
        "amount": 15008.98,
        "brokerage": 22.51,
        "tax": 7.5,
    },
    {
        "date": "12-Mar-24",
        "refNo": "Txn101",
        "account": "Dummy-123",
        "instrument": "Hindustan Unilever Ltd",
        "product": "Equity",
        "securityCode": "HINDUNILVR",
        "txnType": "Sell",
        "quantity": 9,
        "price": 2534.51,
        "amount": 22810.59,
        "brokerage": 72.23,
        "tax": 24.08,
    },
    {
        "date": "15-Mar-24",
        "refNo": "Txn102",
        "account": "Dummy-123",
        "instrument": "Cash",
        "product": "Current account",
        "txnType": "Deposit",
        "quantity": None,
        "price": None,
        "amount": 55067,
        "brokerage": 0,
        "tax": 0,
    },
    {
        "date": "18-Mar-24",
        "refNo": "Txn107",
        "account": "Dummy-123",
        "instrument": "Cash",
        "product": "Current account",
        "txnType": "Deposit",
        "quantity": None,
        "price": None,
        "amount": 24724,
        "brokerage": 0,
        "tax": 0,
    },
    {
        "date": "25-Mar-24",
        "refNo": "Txn114",
        "account": "Dummy-123",
        "instrument": "Shriram Finance",
        "product": "Equity",
        "securityCode": "SHRIRAMFIN",
        "txnType": "Sell",
        "quantity": 5,
        "price": 10255.48,
        "amount": 51277.4,
        "brokerage": 76.92,
        "tax": 25.64,
    },
    {
        "date": "27-Mar-24",
        "refNo": "Txn108",
        "account": "Dummy-123",
        "instrument": "Shriram Finance",
        "product": "Equity",
        "securityCode": "SHRIRAMFIN",
        "txnType": "Buy",
        "quantity": 20,
        "price": 10862.37,
        "amount": 217247.4,
        "brokerage": 325.87,
        "tax": 108.62,
    },
    {
        "date": "29-Mar-24",
        "refNo": "Txn111",
        "account": "Dummy-123",
        "instrument": "Cash",
        "product": "Current account",
        "txnType": "Deposit",
        "quantity": None,
        "price": None,
        "amount": 37337,
        "brokerage": 0,
        "tax": 0,
    },
    {
        "date": "01-Jun-24",
        "refNo": "Txn110",
        "account": "Dummy-123",
        "instrument": "Cash",
        "product": "Current account",
        "txnType": "Withdrawal",
        "quantity": None,
        "price": None,
        "amount": 37628,
        "brokerage": 0,
        "tax": 0,
    },
    {
        "date": "02-Aug-24",
        "refNo": "Txn116",
        "account": "Dummy-123",
        "instrument": "Hindustan Unilever Ltd",
        "product": "Equity",
        "securityCode": "HINDUNILVR",
        "txnType": "Buy",
        "quantity": 15,
        "price": 2691.71,
        "amount": 40375.65,
        "brokerage": 40.38,
        "tax": 20.19,
    },
    {
        "date": "27-Aug-24",
        "refNo": "Txn105",
        "account": "Dummy-123",
        "instrument": "Cash",
        "product": "Current account",
        "txnType": "Withdrawal",
        "quantity": None,
        "price": None,
        "amount": 12143,
        "brokerage": 0,
        "tax": 0,
    },
    {
        "date": "28-Aug-24",
        "refNo": "Txn106",
        "account": "Dummy-123",
        "instrument": "Adani Green Energy Ltd",
        "product": "Equity",
        "securityCode": "ADANIGREEN",
        "txnType": "Buy",
        "quantity": 9,
        "price": 1019.97,
        "amount": 9179.73,
        "brokerage": 9.18,
        "tax": 4.59,
    },
    {
        "date": "06-May-24",
        "refNo": "Txn124",
        "account": "Dummy-123",
        "instrument": "Tata Motors",
        "product": "Equity",
        "securityCode": "TATAMOTORS",
        "txnType": "Buy",
        "quantity": 24,
        "price": 945,
        "amount": 22680,
        "brokerage": 27.3,
        "tax": 3.56,
    },
    {
        "date": "12-Apr-24",
        "refNo": "Txn113",
        "account": "Dummy-123",
        "instrument": "Adani Green Energy Ltd",
        "product": "Equity",
        "securityCode": "ADANIGREEN",
        "txnType": "Buy",
        "quantity": 8,
        "price": 1155.09,
        "amount": 9240.72,
        "brokerage": 9.24,
        "tax": 4.62,
    },
    {
        "date": "24-Oct-24",
        "refNo": "Txn125",
        "account": "Dummy-123",
        "instrument": "Shriram Finance",
        "product": "Equity",
        "securityCode": "SHRIRAMFIN",
        "txnType": "5:1 stock split",
        "quantity": None,
        "price": None,
        "amount": None,
        "brokerage": 0,
        "tax": 0,
    },
    {
        "date": "19-Nov-24",
        "refNo": "Txn119",
        "account": "Dummy-123",
        "instrument": "Hindustan Unilever Ltd",
        "product": "Equity",
        "securityCode": "HINDUNILVR",
        "txnType": "Buy",
        "quantity": 13,
        "price": 2472.02,
        "amount": 32136.26,
        "brokerage": 32.14,
        "tax": 16.07,
    },
    {
        "date": "12-Nov-24",
        "refNo": "Txn100",
        "account": "Dummy-123",
        "instrument": "Cash",
        "product": "Current account",
        "txnType": "Deposit",
        "quantity": None,
        "price": None,
        "amount": 48785,
        "brokerage": 0,
        "tax": 0,
    },
    {
        "date": "19-Dec-24",
        "refNo": "Txn104",
        "account": "Dummy-123",
        "instrument": "Cash",
        "product": "Current account",
        "txnType": "Deposit",
        "quantity": None,
        "price": None,
        "amount": 42006,
        "brokerage": 0,
        "tax": 0,
    },
    {
        "date": "20-Dec-24",
        "refNo": "Txn103",
        "account": "Dummy-123",
        "instrument": "Shriram Finance",
        "product": "Equity",
        "securityCode": "SHRIRAMFIN",
        "txnType": "Dividend",
        "quantity": 23,
        "price": None,
        "amount": 3.23,
        "brokerage": 0,
        "tax": 0,
    },
    {
        "date": "22-Nov-24",
        "refNo": "Txn117",
        "account": "Dummy-123",
        "instrument": "Cash",
        "product": "Current account",
        "txnType": "Deposit",
        "quantity": None,
        "price": None,
        "amount": 38942,
        "brokerage": 0,
        "tax": 0,
    },
]

# Convert date format to datetime
def convert_date(date_str):
    return datetime.strptime(date_str, "%d-%b-%y")

# Update transactions with datetime format
for txn in transactions:
    txn["date"] = convert_date(txn["date"])

# Insert transactions into MongoDB
db.transactions.insert_many(transactions)

print("Transactions inserted successfully!")
